clear;
close all;
clf;
clc;

A = [-2, -0.02; 1, -10];
B = [2; 0];
C = [0, 1];
D = 0;
sys_open = ss(A, B, C, D);
P = [-10, -15]; 
K = place(A, B, P);
disp('Ο πίνακας κερδών K είναι:');
disp(K);
A_cl = A - B*K;
kr = -1 / (C * inv(A_cl) * B);
disp('Το κέρδος kr είναι:');
disp(kr);
B_cl = B * kr;
sys_closed = ss(A_cl, B_cl, C, D);
t = 0:0.01:2;
step(sys_closed, t);
title('Απόκριση Ταχύτητας Κινητήρα (Κλειστός Βρόχος) σε r=1');
xlabel('Χρόνος (sec)');
ylabel('Ταχύτητα \omega (rad/s)');
grid on;
